# deploy dist directory to Gitlab pages

image: busybox

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - dist
  only:
    - main
